import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Typewriter from "typewriter-effect";
import { Avatar, AvatarBadge, AvatarGroup } from "@chakra-ui/react";
import { Flex, Spacer, Center } from "@chakra-ui/react";
import { FcDown } from "react-icons/fc";
import { FaArrowDown } from "react-icons/fa";

export default function Home() {
  return (
    <div className={styles.parentContainer}>
      <Head>
        <title>Thank You</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.asideAvatar}>
          <Avatar
            size="2xl"
            name="Sayuri Kamble"
            src="https://pbs.twimg.com/profile_images/1352056293456900099/8A0w4Ueq_400x400.jpg"
          />

          <h1 className={styles.titleXl}>Hey, I am Sayuri Kamble</h1>
          <p className={styles.avatarDescrip}>
            A young 18 years old girl on a journey to enchance as a Fullstack
            Web Developer. <br /> I code in HTML, CSS, Javascript and React.{" "}
            <br /> I love communicating, making new connections & discussing
            about ideas, projects and startup. I write articles on hashnode.{" "}
            <br />
            Also I document my journey on some social networking sites
          </p>
        </div>

        <div className={styles.asideContent}>
          <h2 className={styles.title}>
            <Typewriter
              onInit={(typewriter) => {
                typewriter.typeString("Thanks for this opportunity!").start();
              }}
            />
          </h2>

          <p className={styles.code}>
            Thanks for reaching out! The role you mentioned certainly sounds
            like an interesting job, and I appreciate your consideration.
            <br />I am a First Year Student and I am not looking out this
            commitment as of now. <br />
            That said, if I find myself looking to make a change in the future,
            I’ll be sure to get in touch <br />I would love to stay connected
            Thanks again!
          </p>

          <p className={styles.asideContentDescrip}>
            I am consistently working on my skillset, checkout my hardwork{" "}
            <a target="new" href="https://neo-sayuk-portfolio.netlify.app/">
              <span className={styles.link}> here </span>
            </a>
          </p>

          <div className={styles.navigateBtnsDiv}>
            {/* <button className={styles.navigateBtn}>
              <Link href={`/projects`}>
                <a>Go to Projects</a>
              </Link>
            </button>

            <button className={styles.navigateBtn}>
              <Link href={`/blogs`}>
                <a>Go to Blogs</a>
              </Link>
            </button> */}
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        Made with{" "}
        <span style={{ color: "yellow", marginLeft: "2.2px" }}> gratitude</span>{" "}
      </footer>
    </div>
  );
}
