import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Typewriter from 'typewriter-effect';



export default function Home() {


  return (
    <div className={styles.container}>
      <Head>
        <title>Thank You</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>
          <Typewriter options={{
            strings: ['Thank You for this amazing opportunity'],
            autoStart: true,
            loop:true
          }}/>
        </h2>
      

        <Link href={`/projects`}>
          <a>Go to Projects</a>
        </Link>

        <Link href={`/blogs`}>
          <a>Go to Blogs</a>
        </Link>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
