import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Typewriter from "typewriter-effect";
import { Avatar, AvatarBadge, AvatarGroup } from "@chakra-ui/react";
import { Flex, Spacer, Center } from "@chakra-ui/react";

export default function Home() {
  return (
    <div className={styles.parentContainer}>
      <Head>
        <title>Thank You</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.asideAvatar}>
          <Avatar
            size="2xl"
            name="Sayuri Kamble"
            src="https://pbs.twimg.com/profile_images/1352056293456900099/8A0w4Ueq_400x400.jpg"
          />

          <h1 className={styles.titleXl}>Hey, I am Sayuri Kamble</h1>
          <p className={styles.avatarDescrip}>
            A young 18 years old girl on a journey to enchance as a Fullstack
            Web Developer. <br /> I code in HTML, CSS, Javascript and React.{" "}
            <br /> I love communicating, making new connections & discussing
            about ideas, projects and startup. I write articles on hashnode.{" "}
            <br />
            Also I document my journey on some social networking sites
          </p>
        </div>

        <div className={styles.asideContent}>
          <h2 className={styles.title}>
            <Typewriter
              options={{
                strings: ["Thank You for this amazing opportunity"],

                autoStart: true,
                // loop: true,
              }}
            />
          </h2>

          <p className={styles.asideContentDescrip}>
            Thanks for allowing me a wonderfull chance to work along, but...{" "}
            <br />I am a First Year Student and I am not looking out this
            commitment as of now!
          </p>

          <Link href={`/projects`}>
            <a>Go to Projects</a>
          </Link>

          <Link href={`/blogs`}>
            <a>Go to Blogs</a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
